spring.application.name=pbl5

spring.datasource.url=jdbc:postgresql://localhost:5432/pbl5
spring.datasource.username=postgres
spring.datasource.password=123456

jwt.secret=5W/gsQQnANpfq28MssMTclP3MUJ6blNTAMEvaKn/mq0=
jwt.expiration=86400000

server.address=0.0.0.0
server.port=8080

app.base-url=http://localhost:8080

ai.tcp.host=127.0.0.1
ai.tcp.port=5000
